apiVersion: apps/v1
kind: Deployment
metadata:
  name: { { include "arroyo-chart.fullname" . } }
  labels:
    app: { { include "arroyo-chart.name" . } }
spec:
  replicas: { { .Values.replicaCount } }
  selector:
    matchLabels:
      app: { { include "arroyo-chart.name" . } }
  template:
    metadata:
      labels:
        app: { { include "arroyo-chart.name" . } }
    spec:
      containers:
        - name: arroyo-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: { { .Values.image.pullPolicy } }
          ports:
            - containerPort: { { .Values.service.targetPort } }
          resources: { { - toYaml .Values.resources | nindent 12 } }
---

