apiVersion: v1
kind: Service
metadata:
  name: {{ include "arroyo-chart.fullname" . }}
  labels:
    app: {{ include "arroyo-chart.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    app: {{ include "arroyo-chart.name" . }}
