# templates/pvc.yaml

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "rust-backend.fullname" . }}-pvc
spec:
  accessModes: {{ .Values.persistence.accessModes | toJson }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
